# Generated by Django 4.2.11 on 2024-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_myuser_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='hit1',
            field=models.IntegerField(blank=True, default=0, verbose_name='1_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit10',
            field=models.IntegerField(blank=True, default=0, verbose_name='10_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit11',
            field=models.IntegerField(blank=True, default=0, verbose_name='11_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit12',
            field=models.IntegerField(blank=True, default=0, verbose_name='12_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit13',
            field=models.IntegerField(blank=True, default=0, verbose_name='13_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit14',
            field=models.IntegerField(blank=True, default=0, verbose_name='14_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit15',
            field=models.IntegerField(blank=True, default=0, verbose_name='15_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit16',
            field=models.IntegerField(blank=True, default=0, verbose_name='16_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit17',
            field=models.IntegerField(blank=True, default=0, verbose_name='17_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit18',
            field=models.IntegerField(blank=True, default=0, verbose_name='18_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit19',
            field=models.IntegerField(blank=True, default=0, verbose_name='19_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit2',
            field=models.IntegerField(blank=True, default=0, verbose_name='2_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit20',
            field=models.IntegerField(blank=True, default=0, verbose_name='20_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit3',
            field=models.IntegerField(blank=True, default=0, verbose_name='3_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit4',
            field=models.IntegerField(blank=True, default=0, verbose_name='4_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit5',
            field=models.IntegerField(blank=True, default=0, verbose_name='5_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit6',
            field=models.IntegerField(blank=True, default=0, verbose_name='6_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit7',
            field=models.IntegerField(blank=True, default=0, verbose_name='7_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit8',
            field=models.IntegerField(blank=True, default=0, verbose_name='8_try'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='hit9',
            field=models.IntegerField(blank=True, default=0, verbose_name='9_try'),
        ),
    ]
