# Generated by Django 4.2.11 on 2024-04-01 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_myuser_hit1_myuser_hit10_myuser_hit11_myuser_hit12_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='myuser',
            old_name='Рейтинг',
            new_name='score',
        ),
    ]
