# Generated by Django 4.2.5 on 2024-04-19 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_rename_рейтинг_myuser_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='count_play',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='count_play'),
        ),
    ]
