# Generated by Django 4.2.5 on 2024-04-21 21:56

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_myuser_count_play'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_hit',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=0, size=None),
        ),
        migrations.AddField(
            model_name='myuser',
            name='last_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=0, size=None),
        ),
    ]
