# Generated by Django 4.2.5 on 2024-04-21 22:00

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_myuser_last_hit_myuser_last_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='last_number',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=0, size=None),
        ),
    ]
