# Generated by Django 4.2.5 on 2024-04-21 22:02

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_myuser_last_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_score',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, default=0, size=None), size=None),
        ),
    ]
