# Generated by Django 4.2.5 on 2024-04-21 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_myuser_last_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='last_hit',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_number',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
